name: wallet_core
author: Lior Rabin <lior9586@gmail.com>
version: 0.0.1+9
homepage: https://github.com/fuseio/wallet_core
description: wallet core package
environment: 
  sdk: '>=2.0.0-dev.68.0 <3.0.0'
dependencies: 
  bip32: ^1.0.5
  bip39: ^1.0.3
  hex: ^0.1.2
  web3dart: ^1.2.1
  http: ^0.12.0
  flutter: 
    sdk: flutter
